name: yanke.io
description: Yet Another Happy Coder.
meta_description: "Yet Another Happy Coder."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
baseurl:        '/'
url:            'http://blog.yanke.io'
author:         'YANKE Guo'
author_avatar:  '/assets/images/profile.png'
author_email:   'hi@yanke.io'
