name: YANKE.IO
description: Yet Another Nerd.
meta_description: "Another Happy Nerd."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
baseurl:        '/'
url:            'http://blog.yanke.io'
author:         'YANKE Guo'
