name: yanke.io
description: Yet Another Happy Coder.
meta_description: "yanke,coder,ruby,ios,blog,IT,developer"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
baseurl:        '/'
url:            'http://blog.yanke.io'
author:         'YANKE Guo'
author_avatar:  '/assets/images/profile.png'
author_email:   'hi@yanke.io'
author_twitter: 'https://twitter.com/yanke_guo'
author_github:  'https://github.com/yanke-guo'
author_weibo:   'http://weibo.com/didierguo'
